### PR TITLE
Add text direction

### PR DESCRIPTION
**Pull request by vyorkin**
Add `direction` CSS property along with the new `TextDirection` type and `ltr` / `rtl` values.

### CODE REVIEW

**Comment by vyorkin** [comment]
Please, don't merge yet, going to refactor this to replace newtype with sum type like we did in #95

**Comment by vyorkin** [comment]
Refactored, rebased :ok_hand:

**Review by JordanMartinez — APPROVED** [review]
Aside from the need to add an entry to the Changelog file, this change looks good to me. However, we might need to complete it via a separate PR.

**Review by thomashoneyman — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Superceded by #137

**Pull request closed without merging**
