### PR TITLE
Added table selector

### PR DESCRIPTION
**Pull request by plurip-software**
**Missing Table Selector**

While using purescript-halogen-css I became aware of the non-existance of a separate table selector.

---

**Checklist:**

- [ x] Added specific table selector as 'table_' (table wasn't available as a function name since it is already used for the ' display table' in CSS.Display).

### CODE REVIEW

**Comment by nsaunders** [comment]
Hi @plurip-software, thanks for your submission.

Regarding the name conflict, I really appreciate that you maintained backward compatibility by preserving the existing function name. However, since we have other breaking API changes in the pipeline anyway (as of today), it seems like now might be a good time to resolve that conflict by renaming the existing `table` function to `displayTable` ([as has been done in Clay](https://github.com/sebastiaanvisser/clay/commit/1ae85de3f4177763b78a8d2a9ef952d9a2aab5ab)). What do you think?

**Comment by plurip-software** [comment]
Sounds good !

**Comment by nsaunders** [comment]
Excellent, thanks @plurip-software. Would you be interested in adding another commit to make that change? If not, I can do it for you. Just let me know!

**Comment by nsaunders** [comment]
Looks great -- thanks!

**Pull request merged**
