### PR TITLE
add 'ch' sizing unit

### PR DESCRIPTION
**Pull request by safareli**

### CODE REVIEW

**Comment by safareli** [comment]
i use it here https://github.com/safareli/purescript-halogen-datepicker/blob/344193a83ef709959c2a444489ab8d9e4897bf1e/src/Halogen/DatePicker/Component/Internal/Elements.purs#L122

**Comment by garyb** [comment]
What's wrong with a good ol' `em` or `rem`? :wink:

I guess we can merge this, as it is standard, but since it acts differently in IE than all the other browsers it's not something I think we actually use.

**Comment by safareli** [comment]
it's `Relative to width of the "0" (zero)`.

> acts differently in IE

in which version?

**Comment by garyb** [comment]
Yeah, I realise what the size is, my point was `rem` / `em` are relative to the font also, so using `0` rather than `m` as a basis for the size doesn't really seem all that useful.

> in which version?

All versions! http://www.caniuse.com/#feat=ch-unit

**Comment by safareli** [comment]
that's sad :/ wanted to use it for width of number input.
But let's hope for it to be fixed in future IE versions :d

**Comment by garyb** [comment]
It's fixed in Edge at least :)

**Comment by safareli** [comment]
@garyb should we merge this ?

**Comment by i-am-the-slime** [comment]
I need this. And `ch` has a really nice use case for keeping your text legible by limiting be `max-width: 75ch` in paragraphs for example.

**Comment by JordanMartinez** [comment]
The only browsers that don't currently support this are Opera Mini and IE 11. @garyb Should this PR to add the `ch` unit be reconsidered? I've fixed the merge conflict.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
