### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
Backlinking to purescript-contrib/governance#35

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@JordanMartinez All of the inferred kind annotations here can be fixed to `Type`. We can also replace the use of `foldl1`, which will take care of the issues with this PR.

**Comment by thomashoneyman** [comment]
I'm not sure what the `these` issue is about. It seems to build just fine on its own.

**Comment by kl0tl** [comment]
It seems that https://github.com/purescript-contrib/purescript-these/pull/29 added Test.QuickCheck.Laws.Control.* modules depending on quickcheck and quickcheck-laws under src instead of test. Moving those modules under test will perhaps be enough but the pull request also added arrays and lists dependencies to these, we should also update the package set.

**Comment by kl0tl** [comment]
I opened https://github.com/purescript-contrib/purescript-these/pull/32 and https://github.com/purescript/package-sets/pull/760.

**Pull request merged**
