### PR TITLE
Update import for `lookup`'s new location

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Part of https://github.com/purescript/purescript-profunctor/issues/23

Consequence of purescript/purescript-foldable-traversable#131.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation in the README and/or documentation directory
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
CI will fail until fix here (https://github.com/purescript/purescript-foldable-traversable/pull/133) is merged.

**Review by thomashoneyman — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Pretty sure CI is failing here because of a caching issue... Does that sound right?

**Comment by JordanMartinez** [comment]
Ha! No, it's the `packages.dhall` file.

**Comment by JordanMartinez** [comment]
Looks like I started this PR on a way outdated version of `main`.

**Comment by JordanMartinez** [comment]
Nevermind... We have a sort of chicken-and-egg problem here... The `prepare-0.14` package set does not yet include the updated dependency graphs (i.e. https://github.com/purescript/package-sets/pull/807). Thus, when CI here attempts to build, it's using the dependency graph before we did the `functors` migration. To get this CI to pass, we have to merge https://github.com/purescript/package-sets/pull/807 first.

**Pull request merged**
